image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080
    onOpen: open-preview

tasks:
  - init: 
      pip install -r requirements.txt
    command: 
      python manage.py runserver 0.0.0.0:8080

vscode:
  extensions:
    # postgres
    - ckolkman.vscode-postgres@1.1.17:gE0nzV6f9gqMRqOHQT6cvw==

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
